import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import SessionView from '../../components/SessionView';
import type { Session, Message } from '../../types/home';
import { AGENT_COMMANDS } from '../../lib/agentCommands';

const mockSession: Session = {
  id: 'test-session-1',
  name: 'Test Session',
  projectId: 'proj-1',
  repoPath: '/path/to/repo',
  runnerId: 'runner-1',
  agentType: 'agy',
  status: 'idle',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

const mockMessages: Message[] = [
  {
    id: 'msg-url-path-1',
    sessionId: 'test-session-1',
    role: 'user',
    content: '/user/id',
    createdAt: new Date().toISOString(),
  },
];

const props: React.ComponentProps<typeof SessionView> = {
  selectedSession: mockSession,
  selectedSessionId: mockSession.id,
  isNewSession: false,
  isNewDraft: false,
  messages: mockMessages,
  execCards: new Map(),
  returnMsgIds: new Set(),
  runners: [],
  projects: [],
  runnerAgents: [],
  runnerId: 'runner-1',
  agentType: 'agy',
  repoPath: '/path/to/repo',
  prompt: '',
  isAgentRunning: false,
  isRunning: false,
  isArchived: false,
  onUnarchiveSession: () => {},
  isDraftSession: false,
  isDraftAutoSend: false,
  draftTrigger: 'manual',
  draftAt: null,
  sendScheduledAt: null,
  onSetSendScheduledAt: () => {},
  pendingSendTrigger: null,
  onSetPendingSendTrigger: () => {},
  canSubmit: false,
  menuOpen: false,
  scriptSubMenuOpen: false,
  showCommandMenu: false,
  commandMenuIndex: -1,
  scriptHistory: {},
  isCheckingGitChanges: false,
  hasGitChanges: false,
  isGitRepo: true,
  runnerDropdownOpen: false,
  agentDropdownOpen: false,
  menuRef: { current: null },
  runnerSelectRef: { current: null },
  agentSelectRef: { current: null },
  chatBottomRef: { current: null },
  textareaRef: { current: null },
  renderMessageContent: (c: string) => c,
  getSendTooltip: () => '',
  isAgentAvailable: () => true,
  onSetMenuOpen: () => {},
  onSetScriptSubMenuOpen: () => {},
  onSetRunnerId: () => {},
  onSetRepoPath: () => {},
  onSetAgentType: () => {},
  onSetIsNewDraft: () => {},
  onSetDraftTrigger: () => {},
  onSetDraftAt: () => {},
  onSetRunnerDropdownOpen: () => {},
  onSetAgentDropdownOpen: () => {},
  onSetFsCurrentPath: () => {},
  onSetFsModalOpen: () => {},
  onSetFsRunnerId: () => {},
  ws: null,
  onViewLog: () => {},
  onShowCommand: () => {},
  onShowPrompt: () => {},
  onStopExecCard: () => {},
  onRestartScriptCard: () => {},
  onRerunCard: () => {},
  onSubmit: () => {},
  onArchiveSession: () => {},
  onTogglePinSession: () => {},
  onSendDraftNow: () => {},
  onToggleDraftTrigger: () => {},
  onCancelTodo: () => {},
  onSendTodoNow: () => {},
  onChangeTodoTrigger: () => {},
  onPromptChange: () => {},
  onKeyDown: () => {},
  onRunScript: () => {},
  onDeleteSession: () => {},
  onOpenShellModal: () => {},
  onOpenFileBrowser: () => {},
  onShowDiff: () => {},
  onShowCommits: () => {},
  onOpenFilePath: () => {},
  onOpenRenameModal: () => {},
  onGoToProject: () => {},
  onNewSession: () => {},
  agentCommands: AGENT_COMMANDS,
  onNewSessionCommand: () => {},
  onRenameSessionCommand: () => {},
  onExecuteAgentCommand: () => {},
  onSelectScriptCommand: () => {},
  onTriggerRunFileSelector: () => {},
  onSwitchAgent: () => {},
  pendingFiles: [],
  onSelectFiles: () => {},
  onRemovePendingFile: () => {},
};

const html = renderToStaticMarkup(React.createElement(SessionView, props));

const menuProps = {
  ...props,
  menuOpen: true,
  scriptSubMenuOpen: true,
  scriptHistory: { 'npm test': 3, 'npm run lint': 5, 'npm run build': 2 },
};
const menuHtml = renderToStaticMarkup(React.createElement(SessionView, menuProps));

console.log(
  JSON.stringify({
    hasUserMessageCard: html.includes('user-message-card'),
    hasUserAgentCommandCard: html.includes('user-agent-command-card'),
    htmlSnippet: html.slice(html.indexOf('exec-card'), html.indexOf('exec-card') + 120),
    hasHistoryScript: menuHtml.includes('menu-run-history-npm-run-build'),
    hasHistoryScripts: menuHtml.includes('menu-run-history-npm-run-lint') && menuHtml.includes('menu-run-history-npm-test'),
    hasDuplicateHistoryScriptExcluded: !menuHtml.includes('menu-run-history-npm-run-build'),
    hasSelectButton: menuHtml.includes('menu-run-script-select'),
    hasEditScriptsButton: menuHtml.includes('menu-manage-scripts'),
  })
);
